export const GAME_START = 'GAME_START';
export const GAME_RUNNING = 'GAME_RUNNING';
export const GAME_LOST_LIFE_PAUSED = 'GAME_LOST_LIFE_PAUSED';
export const GAME_OVER_WON = 'GAME_OVER_WON';
export const GAME_OVER_LOST = 'GAME_OVER_LOST';
